version: "3"
services:
  specialist:
    image: breadlyy/simplepsy-specialist:latest
    ports:
      - "8081:8081"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  session:
    image: breadlyy/simplepsy-session:latest
    ports:
      - "8083:8083"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  scoring:
    image: breadlyy/simplepsy-scoring:latest
    ports:
      - "8084:8084"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  problem:
    image: breadlyy/simplepsy-problem:latest
    ports:
      - "8087:8087"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  customer:
    image: breadlyy/simplepsy-customer:latest
    ports:
      - "8080:8080"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  client:
    image: breadlyy/simplepsy-client:latest
    ports:
      - "8086:8086"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087
  notifications:
    image: breadlyy/simplepsy-notification:latest
    ports:
      - "8085:8085"
    environment:
      - CUSTOMER_SERVICE_URL=http://customer:8080
      - SPECIALIST_SERVICE_URL=http://specialist:8081
      - SESSION_SERVICE_URL=http://session:8083
      - SCORING_SERVICE_URL=http://scoring:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
      - CLIENT_SERVICE_URL=http://client:8086
      - PROBLEM_SERVICE_URL=http://problem:8087