spring:
  data:
    mongodb:
      uri: mongodb://psyApp:123@93.95.97.176:27017/psyDb?authSource=admin
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  zipkin:
    baseUrl: http://127.0.0.1:9411/
server:
  port: 8083