openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: тут мы будем описывать Заказчика для проекта "Понятная практика"
  contact:
    email: raznomazovvm@gmail.com
  version: 0.0.1
externalDocs:
  description: про наш проект можно почитать тут
  url: https://github.com/Kroshy1984/SimplePsy/wiki/%D0%9F%D0%BE%D0%BD%D1%8F%D1%82%D0%BD%D0%B0%D1%8F-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0
servers:
  - url: http://93.95.97.176:8080/SimplePsy/V1/
tags:
  - name: сustomer
    description: Тот, кто звонит психологу
    externalDocs:
      description: Find out more
      url: https://github.com/Kroshy1984/SimplePsy/wiki/%D0%97%D0%B0%D0%BA%D0%B0%D0%B7%D1%87%D0%B8%D0%BA
  - name: client
    description: тот, кто пришел к психологу на прием
    externalDocs:
      description: Find out more about our store
      url: https://github.com/Kroshy1984/SimplePsy/wiki/%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82
  - name: user
    description: Operations about user
paths:
  /customer:
    put:
      tags:
        - customer
      summary: Update an existing pet
      description: Обновляем данные заказчика по id
      operationId: updateCustomer
      requestBody:
        description: Обновляем данные о Заказчике
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
    post:
      tags:
        - customer
      summary: Add a new customer to the base
      description: Добавляем нового заказчика в базу
      operationId: addCustomer
      requestBody:
        description:  Добавляем нового заказчика в базу
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'          
        '405':
          description: Invalid input
  /customer/id:
    delete:
      tags:
        - customer
      summary: Удаляем заказчика из базы
      description: Удаляем заказчика из базы
      operationId: deleteCustomer
      responses:
        '200':
          description: Successful operation
          content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'          
        '405':
          description: Invalid input
 
components:
  schemas:
    customer:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор заказчика
        name:
          type: string
          description: Имя заказчика
        contact:
          type: object
          items:
            $ref: '#/components/schemas/contact_type'
    contact_type:
      type: object
      properties:
        phone:
          type: string
          description: телефон заказчика
        email:
          type: string
          description: е-мейл заказчика
        tg:
          type: string
          description: аккаунт в телеграмме
