package ru.sfedu.simplepsy.classes.types;

public enum SpecializationType {
    COUNSELLING_PSYCHOLOGIST,
    EDUCATIONAL_PSYCHOLOGIST,
    FAMILY_PSYCHOLOGIST,
    COACH,
    PSYCHOTHERAPIST,
    CLINICAL_PSYCHOLOGIST,
    PSYCHOANALYST,
    GESTALT_THERAPIST,
    ART_THERAPIST,
    HYPNOTHERAPIST,
    NLP_PSYCHOLOGIST
}
